// Skincare planner — DEFAULT routine (used as initial seed only;
// after first load the routine lives in Firestore and can be edited in-app)
window.SKINCARE_DATA = [
  { name: 'Понедельник', short: 'Пн', theme: 'День ретиноида', mood: 'Renewal',
    tip: 'Вечером — Crystal Retinal. Кожа должна быть СУХОЙ 15–20 минут перед нанесением. Ретиноид наносить последним активом.',
    morning: [
      { n: 'Medicube Air Shot', note: '5 минут, особенно под глаза', kind: 'device' },
      { n: 'Умывание', note: 'Мягкое средство, тёплая вода, промокнуть', kind: 'cleanse' },
      { n: 'Mixsoon Bean Essence', note: '2–3 капли на влажную кожу', kind: 'serum' },
      { n: 'Avène Vitamin Activ Cg', note: 'Витамин C — сияние и защита', kind: 'serum' },
      { n: 'Medicube Triple Collagen', note: 'Увлажнение', kind: 'cream' },
      { n: 'Vichy Neovadiol Rose Yeux', note: 'Крем для век, похлопывая', kind: 'eye' },
      { n: 'Avène SPF 50', note: 'Обязательно, каждый день', kind: 'spf' },
    ],
    evening: [
      { n: 'Очищение', note: 'Снять SPF и загрязнения', kind: 'cleanse' },
      { n: 'Mixsoon Bean Essence', note: 'Первый шаг ухода', kind: 'serum' },
      { n: 'VT PDRN сыворотка', note: 'Защита барьера перед ретиноидом', kind: 'serum' },
      { n: 'LED-маска — красный', note: '15 минут — anti-age', kind: 'led' },
      { n: 'Пауза 15–20 минут', note: 'Кожа должна полностью высохнуть', kind: 'wait' },
      { n: 'Crystal Retinal 3', note: 'Горошина, избегать века и уголки', kind: 'active' },
      { n: 'Пауза 20 минут', note: 'Дать ретиноиду впитаться', kind: 'wait' },
      { n: 'Avène DermAbsolu Nuit', note: 'Финишный крем — питание', kind: 'cream' },
    ]},
  { name: 'Вторник', short: 'Вт', theme: 'RF-лифтинг', mood: 'Sculpt',
    tip: 'Gezatone RF: толстый слой проводящего геля. Круговые движения снизу вверх. Не задерживаться на одной точке дольше трёх секунд.',
    morning: [
      { n: 'Medicube Air Shot', note: '5 минут, особенно под глаза', kind: 'device' },
      { n: 'Умывание', note: 'Мягкое средство, тёплая вода', kind: 'cleanse' },
      { n: 'Mixsoon Bean Essence', note: '2–3 капли на влажную кожу', kind: 'serum' },
      { n: 'Avène Vitamin Activ Cg', note: 'Витамин C', kind: 'serum' },
      { n: 'Vichy Aqualia Thermal', note: 'Лёгкое увлажнение', kind: 'cream' },
      { n: 'Vichy Neovadiol Rose Yeux', note: 'Крем для век', kind: 'eye' },
      { n: 'Avène SPF 50', note: 'Обязательно', kind: 'spf' },
    ],
    evening: [
      { n: 'Очищение', note: 'Снять SPF и загрязнения', kind: 'cleanse' },
      { n: 'Gezatone RF + проводящий гель', note: '15–20 минут: нижняя треть → скулы → лоб', kind: 'device' },
      { n: 'Убрать гель влажной салфеткой', note: '', kind: 'cleanse' },
      { n: 'Mixsoon Bean Essence', note: '', kind: 'serum' },
      { n: 'Numbuzin NAD+ Bio Essence', note: 'Пептиды, энергия клеток', kind: 'serum' },
      { n: 'Avène DermAbsolu Nuit', note: 'Финишный крем', kind: 'cream' },
    ]},
  { name: 'Среда', short: 'Ср', theme: 'Ретиноид + EMS', mood: 'Lift',
    tip: 'Medicube Derma Shot (EMS) — начинать с низкой интенсивности, движения снизу вверх. Особое внимание — овал лица и уголки рта.',
    morning: [
      { n: 'Medicube Air Shot', note: '5 минут, под глаза', kind: 'device' },
      { n: 'Умывание', note: 'Мягкое средство', kind: 'cleanse' },
      { n: 'Mixsoon Bean Essence', note: '2–3 капли на влажную кожу', kind: 'serum' },
      { n: 'Medicube Booster (ионофорез)', note: '5 минут с витамином C', kind: 'device' },
      { n: 'Avène SPF 50', note: 'Обязательно', kind: 'spf' },
    ],
    evening: [
      { n: 'Очищение', note: 'Снять SPF и загрязнения', kind: 'cleanse' },
      { n: 'Medicube Derma Shot (EMS)', note: '10 минут — подтяжка мышц, овал', kind: 'device' },
      { n: 'Mixsoon Bean Essence', note: '', kind: 'serum' },
      { n: 'VT PDRN сыворотка', note: 'Защита барьера', kind: 'serum' },
      { n: 'Пауза 15–20 минут', note: 'Кожа должна высохнуть', kind: 'wait' },
      { n: 'Crystal Retinal 3', note: 'Горошина, избегать века', kind: 'active' },
      { n: 'Пауза 20 минут', note: '', kind: 'wait' },
      { n: 'Avène DermAbsolu Nuit', note: 'Финишный крем', kind: 'cream' },
    ]},
  { name: 'Четверг', short: 'Чт', theme: 'Восстановление + LED', mood: 'Restore',
    tip: 'День восстановления — никаких агрессивных активов. LED зелёный работает с пигментацией и успокаивает кожу.',
    morning: [
      { n: 'Medicube Air Shot', note: '5 минут', kind: 'device' },
      { n: 'Умывание', note: '', kind: 'cleanse' },
      { n: 'Mixsoon Bean Essence', note: '2–3 капли на влажную кожу', kind: 'serum' },
      { n: 'Avène Vitamin Activ Cg', note: 'Витамин C', kind: 'serum' },
      { n: 'Medicube Triple Collagen', note: 'Увлажнение', kind: 'cream' },
      { n: 'Vichy Neovadiol Rose Yeux', note: 'Крем для век', kind: 'eye' },
      { n: 'Avène SPF 50', note: 'Обязательно', kind: 'spf' },
    ],
    evening: [
      { n: 'Очищение', note: '', kind: 'cleanse' },
      { n: 'Mixsoon Bean Essence', note: '', kind: 'serum' },
      { n: 'LED-маска — зелёный', note: '10 минут — пигментация, тон', kind: 'led' },
      { n: 'Numbuzin NAD+ Bio Essence', note: 'Пептиды + лифтинг', kind: 'serum' },
      { n: 'Triple Collagen или DermAbsolu Nuit', note: 'По ощущению', kind: 'cream' },
    ]},
  { name: 'Пятница', short: 'Пт', theme: 'RF-лифтинг', mood: 'Sculpt',
    tip: 'Снова RF. Чередование вт–пт — оптимальная частота для RF-лифтинга. Не забудь проводящий гель.',
    morning: [
      { n: 'Medicube Air Shot', note: '5 минут', kind: 'device' },
      { n: 'Умывание', note: '', kind: 'cleanse' },
      { n: 'Mixsoon Bean Essence', note: '2–3 капли на влажную кожу', kind: 'serum' },
      { n: 'Avène Vitamin Activ Cg', note: 'Витамин C', kind: 'serum' },
      { n: 'Vichy Aqualia Thermal', note: 'Увлажнение', kind: 'cream' },
      { n: 'Vichy Neovadiol Rose Yeux', note: 'Крем для век', kind: 'eye' },
      { n: 'Avène SPF 50', note: 'Обязательно', kind: 'spf' },
    ],
    evening: [
      { n: 'Очищение', note: '', kind: 'cleanse' },
      { n: 'Gezatone RF + проводящий гель', note: '15–20 минут: треть → скулы → лоб', kind: 'device' },
      { n: 'Убрать гель влажной салфеткой', note: '', kind: 'cleanse' },
      { n: 'Mixsoon Bean Essence', note: '', kind: 'serum' },
      { n: 'VT PDRN сыворотка', note: 'Восстановление барьера', kind: 'serum' },
      { n: 'Avène DermAbsolu Nuit', note: 'Финишный крем', kind: 'cream' },
    ]},
  { name: 'Суббота', short: 'Сб', theme: 'Микроиглы Reedle Shot', mood: 'Reset',
    tip: 'VT Reedle Shot — один раз в неделю. Ретиноид сегодня НЕ использовать. После микроигл — VT PDRN, LED фиолетовый, финиш — толстый слой DermAbsolu.',
    morning: [
      { n: 'Medicube Air Shot', note: '5 минут', kind: 'device' },
      { n: 'Умывание', note: '', kind: 'cleanse' },
      { n: 'Mixsoon Bean Essence', note: '2–3 капли на влажную кожу', kind: 'serum' },
      { n: 'Avène Vitamin Activ Cg', note: 'Витамин C', kind: 'serum' },
      { n: 'Medicube Triple Collagen', note: 'Увлажнение', kind: 'cream' },
      { n: 'Vichy Neovadiol Rose Yeux', note: 'Крем для век', kind: 'eye' },
      { n: 'Avène SPF 50', note: 'Обязательно', kind: 'spf' },
    ],
    evening: [
      { n: 'Очищение', note: '', kind: 'cleanse' },
      { n: 'VT Reedle Shot', note: 'Микроиглы, один раз в неделю', kind: 'active' },
      { n: 'VT PDRN сыворотка', note: 'Восстановление после микроигл', kind: 'serum' },
      { n: 'LED-маска — фиолетовый', note: '10 минут — anti-age + антибактериально', kind: 'led' },
      { n: 'Avène DermAbsolu Nuit', note: 'Толстым слоем — максимум питания', kind: 'cream' },
    ]},
  { name: 'Воскресенье', short: 'Вс', theme: 'Ретиноид + LED + MMS', mood: 'Glow',
    tip: 'Утром MMS-режим (микротоки и вибрация) — общий тонус. Вечером — ретиноид по обычной схеме.',
    morning: [
      { n: 'Medicube Air Shot', note: '5 минут', kind: 'device' },
      { n: 'Умывание', note: '', kind: 'cleanse' },
      { n: 'Mixsoon Bean Essence', note: '2–3 капли на влажную кожу', kind: 'serum' },
      { n: 'Medicube MMS режим', note: '10 минут — общий тонус', kind: 'device' },
      { n: 'Avène Vitamin Activ Cg', note: 'Витамин C', kind: 'serum' },
      { n: 'Medicube Triple Collagen', note: 'Увлажнение', kind: 'cream' },
      { n: 'Vichy Neovadiol Rose Yeux', note: 'Крем для век', kind: 'eye' },
      { n: 'Avène SPF 50', note: 'Обязательно', kind: 'spf' },
    ],
    evening: [
      { n: 'Очищение', note: '', kind: 'cleanse' },
      { n: 'Mixsoon Bean Essence', note: '', kind: 'serum' },
      { n: 'VT PDRN сыворотка', note: 'Защита барьера', kind: 'serum' },
      { n: 'LED-маска — красный', note: '15 минут — anti-age', kind: 'led' },
      { n: 'Пауза 15–20 минут', note: 'Кожа должна высохнуть', kind: 'wait' },
      { n: 'Crystal Retinal 3', note: 'Горошина, избегать века', kind: 'active' },
      { n: 'Пауза 20 минут', note: '', kind: 'wait' },
      { n: 'Avène DermAbsolu Nuit', note: 'Финишный крем', kind: 'cream' },
    ]}
];

window.SKINCARE_KIND_LABELS = {
  cleanse: 'Очищение',
  serum: 'Сыворотка',
  cream: 'Крем',
  eye: 'Глаза',
  spf: 'SPF',
  device: 'Прибор',
  led: 'LED',
  active: 'Актив',
  wait: 'Пауза',
};
